[package]
name = "html_to_seed"
version = "0.1.0"
authors = ["TatriX <tatrics@gmail.com>"]
edition = "2018"

[dependencies]
html5ever = "0.23.0"
rustfmt-nightly = "1.3.1"
Inflector = "0.11.4"
rocket = "0.4.2"
